// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dsbmahfforeazlzckruf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRzYm1haGZmb3JlYXpsemNrcnVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk2MjEzNjQsImV4cCI6MjA3NTE5NzM2NH0.7OoEy1GY0dNkxh_Ml9M6lN8NSrm1EL1IiwV0O13yvcg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});